// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2l_DJ5q_8gQzW1nCXCYc0gXDbepqZg4s',
    appId: '1:287425344180:android:c2a426a2e98f64054f9de1',
    messagingSenderId: '287425344180',
    projectId: 'smartbot-72019',
    databaseURL: 'https://smartbot-72019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbot-72019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAne8vwYVurP7wI2cMOc6pQA0vRpbqlYXI',
    appId: '1:287425344180:ios:66a9f768c03e50894f9de1',
    messagingSenderId: '287425344180',
    projectId: 'smartbot-72019',
    databaseURL: 'https://smartbot-72019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartbot-72019.appspot.com',
    iosBundleId: 'com.smartbot.smartbot',
  );

}